version: '3.8'

networks:
  jupyter-network:
    driver: bridge

services:
  jupyterlab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data:/workspace
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    networks:
      - jupyter-network
    runtime: nvidia
